### ISSUE TITLE
Support new Minio console port

### ISSUE THREAD

**Issue by dchiquito** [girder/cookiecutter-girder-4#155]
As of https://github.com/minio/minio/releases/tag/RELEASE.2021-07-08T01-15-01Z Minio hosts the web console on a different port than the API port. By default, the console port is dynamically allocated, so we should explicitly overwrite it in `docker-compose.yml`.
This was working in DANDI's `docker-compose.yml`:
```
  minio:
    image: minio/minio:latest
    # When run with a TTY, minio prints credentials on startup
    tty: true
    command: ["server", "/data", "--console-address", ":${DOCKER_MINIO_CONSOLE_PORT-9001}"]
    environment:
      MINIO_ACCESS_KEY: minioAccessKey
      MINIO_SECRET_KEY: minioSecretKey
    ports:
      - ${DOCKER_MINIO_PORT-9000}:9000
      - ${DOCKER_MINIO_CONSOLE_PORT-9001}:9001
```
